Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2019-10, with the labels that each got.

#196 Add detect_clearsky
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b.rst
  setup.py
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: enhancement, validation

#211 fix monthly, daily, hourly metrics
  docs/source/whatsnew/1.0.0b.rst
  solarforecastarbiter/reports/metrics.py
  solarforecastarbiter/reports/tests/test_metrics.py
Labels: bug, metrics, reports

#212 fix report data load cache check
  docs/source/whatsnew/1.0.0b.rst
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/reports/tests/test_reports_main.py
Labels: bug, reports

#214 fix run_persistence window documentation
  docs/source/whatsnew/1.0.0b.rst
  solarforecastarbiter/reference_forecasts/main.py
Labels: bug, documentation, referencefx

#216 Reindex reference observations to interval_length before posting
  docs/source/whatsnew/1.0.0b.rst
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/crn.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
Labels: IO, bug

#215 finalize release
  docs/source/whatsnew/1.0.0b.rst
Labels: documentation

#219 fix whatsnew formatting
  docs/source/whatsnew/1.0.0b.rst
Labels: documentation

#220 add zenodo badge
  README.md
Labels: infrastructure

#223 Add function to compute an aggregate
  README.md
  docs/source/whatsnew/1.0.0b1.rst
  docs/source/whatsnew/1.0.0b2.rst
  docs/source/whatsnew/index.rst
  requirements.txt
  setup.py
  solarforecastarbiter/tests/test_utils.py
  solarforecastarbiter/utils.py
Labels: enhancement

#221 Metrics preprocessing
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b1.rst
  docs/source/whatsnew/1.0.0b2.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/reports/figures.py
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/reports/metrics.py
  solarforecastarbiter/reports/tests/test_reports_main.py
Labels: metrics
