Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2020-09, with the labels that each got.

#549 relative_euclidean_distance. more pearson tests
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/metrics/deterministic.py
  solarforecastarbiter/metrics/tests/test_deterministic.py
Labels: enhancement, metrics

#551 Probabilistic Forecast timeseries in plotting module
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/plotting/tests/test_plotting_utils.py
  solarforecastarbiter/plotting/tests/test_timeseries.py
  solarforecastarbiter/plotting/timeseries.py
  solarforecastarbiter/plotting/utils.py
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: enhancement

#562 fix timeseries and scatter plot order and opacity
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug, enhancement

#564 kwargs in request_cli_access_token
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
Labels: enhancement

#566 add __blurb__ to fx, obs dataclasses. use in preprocess results dict
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/metrics/preprocessing.py
Labels: bug, reports

#565 fix scatter plot axis range sensitivity to legend width
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug

#570 add workflow to publish package to pypi on 1.* tags
  .github/workflows/publish.yml
Labels: infrastructure

#569 Fix report plotting for probabilistic forecasts with axis=x
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug

#571 adjust how reference forecast names are truncated
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
Labels: referencefx

#545 Convert USCRN elevation to meters
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
Labels: enhancement

#536 Irradiance data at arm sites
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/io/fetch/arm.py
  solarforecastarbiter/io/fetch/tests/test_arm.py
  solarforecastarbiter/io/reference_observations/arm.py
  solarforecastarbiter/io/reference_observations/arm_reference_sites.json
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
  solarforecastarbiter/io/reference_observations/tests/conftest.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/io/reference_observations/tests/test_ref_arm.py
Labels: IO, enhancement

#572 update SRML data to strip trailing nans
  docs/source/whatsnew/1.0.0rc3.rst
  solarforecastarbiter/io/reference_observations/srml.py
  solarforecastarbiter/io/reference_observations/tests/test_srml.py
Labels: bug

#575 fix abbreviation, no period allowed in name
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
Labels: bug

#579 nighttime validation task that accounts for interval length
  docs/source/api.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_validation_tasks.py
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: api, bug, enhancement
