Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2020-04, with the labels that each got.

#374 Plotly timeseries bugs
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
Labels: bug, reports

#382 add cloudy flag to ghi and nighttime to power variables
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/plotting/timeseries.py
  solarforecastarbiter/validation/quality_mapping.py
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_quality_mapping.py
  solarforecastarbiter/validation/tests/test_validation_tasks.py
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: enhancement, validation

#379 fix normalization metrics in reports
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/tests/test_datamodel.py
Labels: bug, enhancement

#367 Added probabilistic forecast support to metrics calculator
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/probabilistic.py
  solarforecastarbiter/metrics/tests/test_calculator.py
Labels: enhancement

#384 Make sure API values are float/int and verify type before validation
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/io/tests/test_io_utils.py
  solarforecastarbiter/io/utils.py
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_validation_tasks.py
Labels: bug, validation

#378 account for uncertainty using deadband
  .gitignore
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/deterministic.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/metrics/tests/test_deterministic.py
  solarforecastarbiter/reports/templates/body.html
  solarforecastarbiter/reports/templates/metrics_meta_table.html
  solarforecastarbiter/tests/test_datamodel.py
Labels: enhancement

#396 enforce metrics order
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/tests/test_calculator.py
Labels: bug, reports

#390 Arm data
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/io/reference_observations/arm.py
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/reference_data.py
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
  solarforecastarbiter/io/reference_observations/tests/conftest.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/io/reference_observations/tests/test_ref_arm.py
  solarforecastarbiter/io/reference_observations/tests/test_reference_data.py
Labels: IO, enhancement

#361 Add support for event observations and forecasts
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/body.html
  solarforecastarbiter/reports/tests/test_reports_main.py
  solarforecastarbiter/tests/data/report_metadata_event.json
  solarforecastarbiter/tests/test_datamodel.py
Labels: datamodel, enhancement

#389 add classes to report tables
  solarforecastarbiter/reports/templates/macros.j2
  solarforecastarbiter/reports/templates/metrics_meta_table.html
  solarforecastarbiter/reports/templates/obsfx_table.html
  solarforecastarbiter/reports/tests/test_macros.py
Labels: enhancement, reports

#387 refactor reference forecast handling to enable skill metric in reports
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/deterministic.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/reports/templates/body.html
  solarforecastarbiter/reports/templates/macros.j2
  solarforecastarbiter/reports/templates/obsfx_table.html
  solarforecastarbiter/reports/tests/test_macros.py
  solarforecastarbiter/reports/tests/test_reports_main.py
  solarforecastarbiter/reports/tests/test_template.py
  solarforecastarbiter/tests/test_cli.py
  solarforecastarbiter/tests/test_datamodel.py
Labels: enhancement, metrics, reports

#394 Add event timeseries support to plotting module
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/plotting/tests/test_plotting_utils.py
  solarforecastarbiter/plotting/tests/test_timeseries.py
  solarforecastarbiter/plotting/timeseries.py
  solarforecastarbiter/plotting/utils.py
Labels: enhancement

#399 Enable loading EventForecasts through Forecast class
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/tests/test_datamodel.py
Labels: bug, datamodel

#395 eliminate most test warnings
  docs/source/whatsnew/1.0.0b5.rst
  requirements.txt
  solarforecastarbiter/metrics/deterministic.py
  solarforecastarbiter/metrics/tests/test_deterministic.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_bokeh_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
  solarforecastarbiter/tests/test_cli.py
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: testing

#388 Fix label cutoff for total metric plots.
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug, reports

#404 Convert report timeseries data to report timezone
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
Labels: bug

#410 Reference forecast value serialization
  solarforecastarbiter/conftest.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/io/utils.py
Labels: bug, reports

#412 fix reference forecast alignment
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
Labels: bug

#416 step plots with plotly
  solarforecastarbiter/plotting/tests/test_plotting_utils.py
  solarforecastarbiter/plotting/utils.py
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug, reports

#421 fix package versions list
  solarforecastarbiter/metrics/deterministic.py
  solarforecastarbiter/metrics/tests/test_deterministic.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/main.py
Labels: bug

#422 clarify data validation section
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/reports/templates/body.html
  solarforecastarbiter/reports/templates/macros.j2
  solarforecastarbiter/reports/tests/test_macros.py
Labels: bug, reports

#408 update beta 5 whats new date, add empty rc1
  docs/source/whatsnew/1.0.0b5.rst
  docs/source/whatsnew/1.0.0rc1.rst
  docs/source/whatsnew/index.rst
Labels: documentation

#392 Add reference load forecast method
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
  solarforecastarbiter/reference_forecasts/utils.py
Labels: enhancement, referencefx
