Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2020-03, with the labels that each got.

#364 discrete xaxes labels closes #363
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/templates/body.html
Labels: bug

#369 Use last timestamp to adjust start time for update reference obs
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/midc.py
  solarforecastarbiter/io/reference_observations/rtc.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/tests/test_cli.py
Labels: IO, enhancement

#366 convert report timeseries to plotly
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b5.rst
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/body.html
  solarforecastarbiter/reports/templates/head.html
  solarforecastarbiter/reports/tests/test_template.py
Labels: enhancement, reports
