Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2020-07, with the labels that each got.

#506 add empty values to metrics table when no metric found
  solarforecastarbiter/reports/templates/html/macros.j2
  solarforecastarbiter/reports/templates/pdf/macros.j2
Labels: bug, reports

#507 fix metric figure div ids
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/tests/test_template.py
Labels: bug, reports

#509 Switch prob. persistence to interval label ending and fix some error formatting
  solarforecastarbiter/io/reference_observations/default_forecasts.py
  solarforecastarbiter/metrics/preprocessing.py
Labels: bug, referencefx, reports

#510 fix ids for cost parameters when special characters are included
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/html/metrics_meta_table.html
  solarforecastarbiter/reports/templates/pdf/base.tex
  solarforecastarbiter/reports/templates/pdf/macros.j2
Labels: bug, reports

#513 Fix report tables
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/reports/templates/html/macros.j2
  solarforecastarbiter/reports/templates/pdf/macros.j2
Labels: bug, reports

#515 adjust margin for long x axis names
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug

#505 finish rc1 whatsnew
  docs/source/api.rst
  docs/source/whatsnew/1.0.0b2.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/reference_forecasts/main.py
Labels: documentation

#529 Fix various persistence bugs
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc2.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/persistence.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
  solarforecastarbiter/reference_forecasts/tests/test_persistence.py
  solarforecastarbiter/tests/test_utils.py
  solarforecastarbiter/utils.py
Labels: bug, referencefx

#519 shaded plots for probabilistic percentile forecasts (axis='y')
  docs/source/whatsnew/1.0.0rc2.rst
  requirements.txt
  setup.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/tests/test_template.py
Labels: enhancement

#535 rc3 whatsnew
  docs/source/whatsnew/1.0.0rc3.rst
  docs/source/whatsnew/index.rst
Labels: documentation
