Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2020-11, with the labels that each got.

#612 make sure hijacking loggers also captures children
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/reports/tests/test_reports_main.py
  solarforecastarbiter/tests/test_utils.py
  solarforecastarbiter/utils.py
Labels: bug

#613 fix issue with prob fx label
  docs/source/whatsnew/1.0.0.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
Labels: bug

#614 Make NWP fetch timeouts configurable
  docs/source/whatsnew/1.0.0.rst
  solarforecastarbiter/io/fetch/__init__.py
  solarforecastarbiter/io/fetch/nwp.py
Labels: IO

#615 add reference aggregates
  docs/source/api.rst
  docs/source/whatsnew/1.0.0.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/reference_aggregates.py
  solarforecastarbiter/io/reference_observations/srml_reference_sites.json
  solarforecastarbiter/io/tests/test_reference_aggregates.py
  solarforecastarbiter/tests/test_cli.py
Labels: enhancement

#616 CLI to backfill observation gaps
  docs/source/api.rst
  docs/source/whatsnew/1.0.0.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/reference_observations/arm.py
  solarforecastarbiter/io/reference_observations/bsrn.py
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/crn.py
  solarforecastarbiter/io/reference_observations/eia.py
  solarforecastarbiter/io/reference_observations/midc.py
  solarforecastarbiter/io/reference_observations/pvdaq.py
  solarforecastarbiter/io/reference_observations/reference_data.py
  solarforecastarbiter/io/reference_observations/rtc.py
  solarforecastarbiter/io/reference_observations/solrad.py
  solarforecastarbiter/io/reference_observations/srml.py
  solarforecastarbiter/io/reference_observations/surfrad.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/io/reference_observations/tests/test_reference_data.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/tests/test_utils.py
  solarforecastarbiter/utils.py
Labels: IO, enhancement

#618 Use tojson filter to escape nested json and html
  docs/source/whatsnew/1.0.0.rst
  solarforecastarbiter/reports/templates/html/load_metadata.html
  solarforecastarbiter/reports/tests/test_jinja_templates.py
Labels: bug

#619 Report total metric ordering
  docs/source/whatsnew/1.0.0.rst
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
  solarforecastarbiter/reports/templates/html/body.html
Labels: bug

#617 Support filling forecast gaps
  docs/source/api.rst
  docs/source/whatsnew/1.0.0.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
  solarforecastarbiter/tests/test_cli.py
Labels: enhancement, referencefx

#620 update 1.0 date
  docs/source/whatsnew/1.0.0.rst
Labels: documentation

#622 minor report text edits
  docs/source/whatsnew/1.0.1.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/pdf/base.tex
Labels: reports
