Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2020-05, with the labels that each got.

#430 fix months and weekdays ordering
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/tests/test_calculator.py
Labels: bug

#433 convert temp coeff to %/C
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/reference_observations/rtc.py
  solarforecastarbiter/pvmodel.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_persistence.py
  solarforecastarbiter/tests/test_pvmodel.py
Labels: api

#435 Split daily validation posting on missing periods and week
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_validation_tasks.py
Labels: enhancement, validation

#437 Generate PDF figures
  azure-pipelines.yml
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
Labels: enhancement, reports

#438 add pvdaq reference sites, fetch, config
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/fetch/pvdaq.py
  solarforecastarbiter/io/fetch/tests/data/pvdaq_2019_data.csv
  solarforecastarbiter/io/fetch/tests/data/pvdaq_2020_data.csv
  solarforecastarbiter/io/fetch/tests/data/pvdaq_metadata.json
  solarforecastarbiter/io/fetch/tests/test_pvdaq.py
  solarforecastarbiter/io/reference_observations/README.md
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/midc.py
  solarforecastarbiter/io/reference_observations/pvdaq.py
  solarforecastarbiter/io/reference_observations/pvdaq_reference_sites.json
  solarforecastarbiter/io/reference_observations/reference_data.py
  solarforecastarbiter/io/reference_observations/rtc.py
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/io/reference_observations/tests/test_ref_pvdaq.py
Labels: IO, enhancement

#439 Render reports to PDF
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/conftest.py
  solarforecastarbiter/reports/figures/fail.pdf
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/data_resampling_postamble
  solarforecastarbiter/reports/templates/data_resampling_preamble
  solarforecastarbiter/reports/templates/data_validation_post_text
  solarforecastarbiter/reports/templates/data_validation_pre_text
  solarforecastarbiter/reports/templates/html/base.html
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/html/empty_base.html
  solarforecastarbiter/reports/templates/html/failure.html
  solarforecastarbiter/reports/templates/html/head.html
  solarforecastarbiter/reports/templates/html/insert_plots.html
  solarforecastarbiter/reports/templates/html/load_metrics.html
  solarforecastarbiter/reports/templates/html/macros.j2
  solarforecastarbiter/reports/templates/html/metrics_meta_table.html
  solarforecastarbiter/reports/templates/html/obsfx_table.html
  solarforecastarbiter/reports/templates/html/pending.html
  solarforecastarbiter/reports/templates/html/versions.html
  solarforecastarbiter/reports/templates/metrics_meta_table_text
  solarforecastarbiter/reports/templates/obsfx_table_text
  solarforecastarbiter/reports/templates/pdf/base.tex
  solarforecastarbiter/reports/templates/pdf/macros.j2
  solarforecastarbiter/reports/templates/version_description
  solarforecastarbiter/reports/tests/test_macros.py
  solarforecastarbiter/reports/tests/test_reports_main.py
  solarforecastarbiter/reports/tests/test_template.py
  solarforecastarbiter/tests/test_cli.py
Labels: enhancement, reports

#441 Add option to report cli to roundtrip through serialization
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  requirements-test.txt
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/utils.py
  solarforecastarbiter/tests/test_cli.py
Labels: reports, testing

#444 fix pvdaq power units
  solarforecastarbiter/io/reference_observations/pvdaq.py
  solarforecastarbiter/io/reference_observations/tests/test_ref_pvdaq.py
Labels: bug

#443 Add dockerfile, test cli command
  .github/workflows/main.yml
  .gitignore
  build/Dockerfile
  build/grib2/config.h
  build/grib2/wgrib2-jasper-2.patch
  build/grib2/wgrib2-nogctpc.patch
  build/tex/texlive.profile
  packages.tex
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/fetch/tests/data/grib/rap.t00z.awp130pgrbf00.grib2
  solarforecastarbiter/io/fetch/tests/data/grib/rap.t00z.awp130pgrbf01.grib2
  solarforecastarbiter/io/fetch/tests/data/grib/rap.t00z.awp130pgrbf02.grib2
  solarforecastarbiter/io/fetch/tests/data/grib/rap.t00z.awp130pgrbf03.grib2
  solarforecastarbiter/io/fetch/tests/test_fetch_nwp.py
  solarforecastarbiter/reports/templates/pdf/base.tex
Labels: infrastructure, testing

#451 change stale, interpolated windows, add daytime-only derived masks
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/plotting/timeseries.py
  solarforecastarbiter/validation/quality_mapping.py
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_quality_mapping.py
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: bug, enhancement, validation

#457 Fix PDF rendering w/ special characters
  packages.tex
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/pdf/base.tex
  solarforecastarbiter/reports/templates/pdf/macros.j2
  solarforecastarbiter/reports/tests/test_template.py
Labels: bug, reports

#462 Only apply derived masks to validated data
  solarforecastarbiter/cli.py
  solarforecastarbiter/validation/quality_mapping.py
  solarforecastarbiter/validation/tests/test_quality_mapping.py
Labels: bug, validation

#455 Add function to compute latest persistence forecasts
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/crn.py
  solarforecastarbiter/io/reference_observations/default_forecasts.py
  solarforecastarbiter/io/reference_observations/srml.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
  solarforecastarbiter/reference_forecasts/utils.py
Labels: enhancement, referencefx

#442 Adjust srml, Add reference obs documentation
  .gitignore
  docs/source/index.rst
  docs/source/reference-observations.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/pvdaq.py
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
  solarforecastarbiter/io/reference_observations/srml.py
  solarforecastarbiter/io/reference_observations/srml_reference_sites.json
  solarforecastarbiter/io/reference_observations/tests/conftest.py
  solarforecastarbiter/io/reference_observations/tests/data/test_site.json
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/io/reference_observations/tests/test_srml.py
Labels: IO, bug, enhancement

#458 add limits checks for power
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_validation_tasks.py
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: enhancement

#445 Refactor Probabilistic Forecast processing in metrics
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/reports/main.py
Labels: metrics

#464 fix persistence bugs
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
Labels: bug, referencefx
