Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2020-06, with the labels that each got.

#469 Beta 6 release
  docs/source/whatsnew/1.0.0b6.rst
  docs/source/whatsnew/1.0.0rc1.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
Labels: IO

#477 Fix power observations for SRML Portland PV site.
  solarforecastarbiter/io/reference_observations/srml_reference_sites.json
Labels: bug

#478 Avoid creating invalid reference persistence forecasts
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/srml.py
  solarforecastarbiter/io/reference_observations/srml_reference_sites.json
  solarforecastarbiter/io/reference_observations/tests/test_common.py
  solarforecastarbiter/io/reference_observations/tests/test_srml.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
  solarforecastarbiter/reference_forecasts/utils.py
Labels: bug, referencefx

#481 add support for parsing climate zones from API
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
Labels: api, datamodel, enhancement

#479 io/api: document use of proxy servers and SSL certificates
  docs/source/api.rst
  solarforecastarbiter/io/api.py
Labels: api, documentation

#482 Add default daily validation and always re-validate observations in a report
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/reports/tests/test_reports_main.py
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_validation_tasks.py
Labels: enhancement, reports, validation

#484 Better data validation
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/tests/test_cli.py
  solarforecastarbiter/validation/quality_mapping.py
  solarforecastarbiter/validation/tasks.py
  solarforecastarbiter/validation/tests/test_quality_mapping.py
  solarforecastarbiter/validation/tests/test_validation_tasks.py
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: enhancement, validation

#434 Add reference probabilistic forecast
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/reference_forecasts/persistence.py
  solarforecastarbiter/reference_forecasts/tests/test_persistence.py
Labels: enhancement

#489 Forecast get mapping
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
Labels: bug

#485 io/fetch: add support for EIA Open Data API
  docs/source/api.rst
  docs/source/reference-observations.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/io/fetch/eia.py
  solarforecastarbiter/io/fetch/tests/data/eia_caiso.json
  solarforecastarbiter/io/fetch/tests/data/eia_caiso_bad.json
  solarforecastarbiter/io/fetch/tests/test_eia.py
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/default_forecasts.py
  solarforecastarbiter/io/reference_observations/eia.py
  solarforecastarbiter/io/reference_observations/reference_data.py
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
  solarforecastarbiter/io/reference_observations/tests/test_ref_eia.py
Labels: enhancement

#487 Implement deterministic cost metrics
  docs/source/api.rst
  docs/source/cli.rst
  docs/source/cost.rst
  docs/source/index.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/deterministic.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/metrics/tests/test_deterministic.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/metrics/tests/test_valuation.py
  solarforecastarbiter/metrics/valuation.py
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/reports/tests/test_macros.py
  solarforecastarbiter/reports/tests/test_template.py
  solarforecastarbiter/tests/data/report_metadata.json
  solarforecastarbiter/tests/test_datamodel.py
Labels: enhancement, metrics

#490 Add probabilistic ref persistence generation fnc
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/io/reference_observations/default_forecasts.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
Labels: enhancement, referencefx

#467 finish initial support for probabilistic forecast reports
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/plotting/utils.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/html/macros.j2
  solarforecastarbiter/reports/templates/html/obsfx_table.html
  solarforecastarbiter/reports/templates/pdf/base.tex
  solarforecastarbiter/reports/templates/pdf/macros.j2
  solarforecastarbiter/reports/tests/test_template.py
  solarforecastarbiter/tests/test_cli.py
Labels: enhancement

#497 Relax day ahead persistence midnight to midnight (UTC) requirement
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
  solarforecastarbiter/reference_forecasts/utils.py
Labels: bug, referencefx

#493 Preprocess forecast fill
  docs/source/api.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/tests/data/report_metadata.json
  solarforecastarbiter/tests/data/report_metadata_event.json
Labels: enhancement

#496 handle serialization/deserialization for prob fx dataframes
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/io/tests/test_io_utils.py
  solarforecastarbiter/io/utils.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/tests/test_cli.py
Labels: bug, reports

#501 Add cost parameters to report body
  docs/source/cost.rst
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/html/head.html
  solarforecastarbiter/reports/templates/html/metrics_meta_table.html
  solarforecastarbiter/reports/templates/metrics_meta_table_text
  solarforecastarbiter/reports/templates/pdf/base.tex
  solarforecastarbiter/reports/templates/pdf/macros.j2
  solarforecastarbiter/reports/tests/test_template.py
Labels: enhancement, reports

#503 fix prob forecast creation from raw report dict
  docs/source/whatsnew/1.0.0rc1.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/tests/test_datamodel.py
Labels: bug
