Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2021-04, with the labels that each got.

#661 fix event validation and summary stats bugs, add event specific summary stats
  docs/source/whatsnew/1.0.2.rst
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/summary.py
  solarforecastarbiter/metrics/tests/test_calculator.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/metrics/tests/test_summary.py
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/tests/test_macros.py
  solarforecastarbiter/reports/tests/test_template.py
  solarforecastarbiter/tests/test_cli.py
Labels: bug

#669 add pnnl data parser
  docs/source/api.rst
  docs/source/reference-observations.rst
  docs/source/whatsnew/1.0.2.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/pnnl.py
  solarforecastarbiter/io/reference_observations/reference_data.py
  solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv
  solarforecastarbiter/io/reference_observations/tests/data/pnnl_data/rldradC1.00.2017/rldradC1.00.20170101.000000.raw.2017010100pnl.sky
  solarforecastarbiter/io/reference_observations/tests/data/pnnl_data/rldradC1.00.2017/rldradC1.00.20170101.010000.raw.2017010101pnl.sky
  solarforecastarbiter/io/reference_observations/tests/data/pnnl_data/rldradC1.00.2017/rldradC1.00.20171231.230000.raw.2017123123pnl.sky
  solarforecastarbiter/io/reference_observations/tests/data/pnnl_data/rldradC1.00.2018/rldradC1.00.20180101.000000.raw.2018010100pnl.sky
  solarforecastarbiter/io/reference_observations/tests/test_ref_pnnl.py
  solarforecastarbiter/io/tests/test_api.py
Labels: enhancement

#673 Add NaNs in detect_clearsky to work around observation gaps
  docs/source/whatsnew/1.0.2.rst
  solarforecastarbiter/validation/tests/test_validator.py
  solarforecastarbiter/validation/validator.py
Labels: bug, validation
