Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2021-09, with the labels that each got.

#722 Fix headers and indexes of report timeseries downloads
  docs/source/whatsnew/1.0.5.rst
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/html/macros.j2
Labels: bug, reports

#727 Reference forecast limit
  docs/source/whatsnew/1.0.5.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
  solarforecastarbiter/reference_forecasts/utils.py
Labels: enhancement

#716 replace ARM GHI with Best Estimate GHI
  docs/source/whatsnew/1.0.5.rst
  solarforecastarbiter/io/fetch/arm.py
  solarforecastarbiter/io/fetch/tests/data/gpmetE15.b1.20180130.000000.cdf
  solarforecastarbiter/io/fetch/tests/data/gpmetE15.b1.20180130.200000.cdf
  solarforecastarbiter/io/fetch/tests/test_arm.py
  solarforecastarbiter/io/reference_observations/arm.py
  solarforecastarbiter/io/reference_observations/arm_reference_sites.json
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/tests/test_common.py
Labels: bug, enhancement

#729 fix season order
  docs/source/whatsnew/1.0.5.rst
  solarforecastarbiter/metrics/calculator.py
  solarforecastarbiter/metrics/tests/test_calculator.py
Labels: bug, metrics, reports

#728 Use greater than or equal to in resample check
  docs/source/whatsnew/1.0.5.rst
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
Labels: bug

#731 Finalize 1.0.5 whats new
  docs/source/whatsnew/1.0.5.rst
  setup.py
Labels: documentation
