Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2021-07, with the labels that each got.

#681 implement report_parameters.timezone
  docs/source/whatsnew/1.0.2.rst
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/tests/test_api.py
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/tests/test_datamodel.py
Labels: enhancement, reports

#645 switch probabilistic persistence forecast to time of day
  docs/source/whatsnew/1.0.2.rst
  solarforecastarbiter/io/reference_observations/common.py
  solarforecastarbiter/io/reference_observations/default_forecasts.py
  solarforecastarbiter/reference_forecasts/main.py
  solarforecastarbiter/reference_forecasts/tests/test_main.py
  solarforecastarbiter/reference_forecasts/utils.py
Labels: bug, referencefx

#689 plot all observation values in time series
  .gitignore
  docs/source/whatsnew/1.0.2.rst
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug

#691 clarify auto reference forecasts are arbiter only
  docs/source/reference-forecasts.rst
  docs/source/whatsnew/1.0.2.rst
Labels: documentation

#688 Fix reference forecast links, add report timerange to links
  docs/source/whatsnew/1.0.2.rst
  solarforecastarbiter/reports/templates/html/macros.j2
  solarforecastarbiter/reports/templates/html/obsfx_table.html
Labels: bug, enhancement

#693 fix ci test TEX repo
  .github/workflows/main.yml
  setup.py
Labels: testing

#701 Adjust summary table header forecast type check
  docs/source/whatsnew/1.0.3.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/tests/test_template.py
Labels: bug
