Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2021-08, with the labels that each got.

#703 Add Interval length and label to report observation labels
  docs/source/whatsnew/1.0.3.rst
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
Labels: bug

#702 fix prob pers time of day when interval_label=ending
  docs/source/whatsnew/1.0.3.rst
  solarforecastarbiter/reference_forecasts/persistence.py
  solarforecastarbiter/reference_forecasts/tests/test_persistence.py
Labels: bug

#704 update whatsnew for 1.0.3
  docs/source/whatsnew/1.0.3.rst
Labels: documentation

#709 fix resampling of obs when fx has different interval label
  docs/source/whatsnew/1.0.4.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/reports/figures/plotly_figures.py
Labels: bug, metrics, reports

#714 update whatsnew for v1.0.4
  docs/source/whatsnew/1.0.4.rst
Labels: documentation

#719 fix DNI projection into POA
  docs/source/whatsnew/1.0.5.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/pvmodel.py
  solarforecastarbiter/reference_forecasts/tests/test_persistence.py
  solarforecastarbiter/tests/test_pvmodel.py
Labels: bug, High Priority

#720 add missing jinja2, pytz dependencies
  docs/source/whatsnew/1.0.5.rst
  requirements.txt
  setup.py
Labels: bug, dependencies
