Repository SolarArbiter/solarforecastarbiter-core, pull requests merged in 2021-12, with the labels that each got.

#752 exclude report outage periods
  docs/source/api.rst
  docs/source/whatsnew/1.0.9.rst
  docs/source/whatsnew/index.rst
  setup.py
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/io/api.py
  solarforecastarbiter/metrics/preprocessing.py
  solarforecastarbiter/metrics/tests/test_preprocessing.py
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/pdf/base.tex
  solarforecastarbiter/reports/tests/test_template.py
  solarforecastarbiter/tests/test_datamodel.py
Labels: enhancement

#758 Outage Tweaks
  solarforecastarbiter/conftest.py
  solarforecastarbiter/datamodel.py
  solarforecastarbiter/reports/main.py
  solarforecastarbiter/reports/templates/html/body.html
  solarforecastarbiter/reports/templates/pdf/base.tex
  solarforecastarbiter/reports/tests/test_template.py
  solarforecastarbiter/tests/test_datamodel.py
Labels: bug, enhancement

#760 Don't print result of outage append call in jinja template
  docs/source/whatsnew/1.0.9.rst
  solarforecastarbiter/reports/template.py
  solarforecastarbiter/reports/templates/html/body.html
Labels: bug

#761 set release date
  docs/source/whatsnew/1.0.9.rst
Labels: documentation

#744 use nanpercentile in persistence ensemble functions
  docs/source/whatsnew/1.0.10.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/reference_forecasts/persistence.py
  solarforecastarbiter/reference_forecasts/tests/test_persistence.py
Labels: bug, referencefx

#764 Add report step logging
  solarforecastarbiter/reports/main.py
Labels: infrastructure

#767 Orca cleanup
  docs/source/whatsnew/1.0.11.rst
  docs/source/whatsnew/index.rst
  solarforecastarbiter/cli.py
  solarforecastarbiter/conftest.py
  solarforecastarbiter/reports/figures/plotly_figures.py
  solarforecastarbiter/reports/tests/test_reports_main.py
Labels: enhancement
